FROM php:7.3-fpm

WORKDIR /code
# RUN apt update -y
# RUN apt install -y epel-release
# RUN apt install -y ruby git vim php
RUN docker-php-ext-install pdo_mysql
# COPY Gemfile Gemfile.lock ./
# RUN bundle install
# CMD nginx -g 'daemon off;'
# CMD tail -f /dev/null
# CMD php -S 0.0.0.0:80
