<?php
/**
 * @file
 * Descriptions of company flag bits.
 */
$coHelp = array(
  'sellcg' => t('This company sells %PROJECT credit.'),
  'flip' => t('Flip the normal Donate vs Buy Credit button choice in our lists of companies.'),
  'sponsored' => t('This company is fiscally sponsored or owned by %PROJECT.'),
  'ourown' => t('This non-sponsored account belongs to %PROJECT.'),
  'ccok' => t('We accept credit card payments for this non-sponsored company.'),
  'private' => t('This company is not to be listed publicly (on promo site, etc.).'),
  'amt' => t('This company can trade %PROJECT credit for cash, even if its balance is less than its credit line floor.'),
//  'fast' => t('Fast checkout -- never ask for photo Id.'),
  'tip' => t('Ask customer what percent tip to add.'),
);
