<?php
/**
 * @file
 * Common Good Web Interface
 *
 * An interface module for the Common Good financial system.
 *
 * Note: to display one of the blocks defined herein on a page, use
 * print render(rweb_block_view('blockname'));)
 * @todo: eliminate rweb_block_info and rweb_block_view by integrating calls to the accounts and footer sections into theme\html.tpl
 */

use CG as r;
use CG\Backend as be;
use CG\Util as u;
use CG\Web as w;

require_once __DIR__ . '/rweb.inc';

define('RWEB_BLOCKS', 'accounts footer');

/**
 * Implements hook_block_info().
 */
function rweb_block_info() {
  $info = [];
  foreach (ray(RWEB_BLOCKS) as $one) {
    $def = array('info' => ucfirst($one) . ' Block');
    $status = 1;
    $def += compact(ray('region status'));
    $info[$one] = $def;
  }
  $info['footer']['cache'] = -1;
  $info['footer']['region'] = 'footer';
  $info['accounts']['region'] = 'accounts';
  return $info;
}

/**
 * Implements hook_block_view().
 */
function rweb_block_view($delta = '') {
  if (in($delta, RWEB_BLOCKS)) return ray('subject content', NULL, w\showForm($delta)); // no subject for blocks
}
