<?php
/**
 * @file
 * rCredits Web Interface
 *
 * An interface module for the rCredits financial system.
 *
 * Note: to display one of the blocks defined herein on a page, use
 * print render(rweb_block_view('blockname'));)
 * @todo: eliminate rweb_block_info and rweb_block_view by integrating calls to the accounts and footer sections into theme\html.tpl
 */

use CG as r;
use CG\Backend as be;
use CG\Util as u;
use CG\Web as w;

require_once __DIR__ . '/../cg.inc';
require_once __DIR__ . '/rweb.inc';

define('RWEB_BLOCKS', 'accounts footer');

/**
 * Implements hook_block_info().
 */
function rweb_block_info() {
  $info = [];
  foreach (ray(RWEB_BLOCKS) as $one) {
    $def = array('info' => ucfirst($one) . ' Block');
    $status = 1;
    $def += compact(ray('region status'));
    $info[$one] = $def;
  }
  $info['footer']['cache'] = -1;
  $info['footer']['region'] = 'footer';
  $info['accounts']['region'] = 'accounts';
  return $info;
}

/**
 * Implements hook_block_view().
 */
function rweb_block_view($delta = '') {
  if (in($delta, RWEB_BLOCKS)) return ray('subject content', NULL, r\Web\showForm($delta)); // no subject for blocks
}

/**
 * Construct a menu item from its list of parts.
 * The last two parts (detail and glyphicon) are used only for submenus (see subMenuHtml())
 */
function makeMenuItem($k, $parts) {
  $types = ['norm' => MENU_NORMAL_ITEM, 'sub' => MENU_LOCAL_TASK, 'dft' => MENU_DEFAULT_LOCAL_TASK, 'call' => MENU_CALLBACK];
  for ($i = 0; $i < 5; $i++) $parts[] = ''; // enough to satisfy list()
  list ($type, $title, $args, $perms, $func) = $parts;
  return w\menu($k, $title, $types[$type], $func ?: 'showForm', $args, $perms);
}

/**
 * Implements hook_menu().
MENU_CALLBACK  Menu type -- A hidden, internal callback, typically used for API calls.
MENU_DEFAULT_LOCAL_TASK  Menu type -- The "default" local task, which is initially active.
MENU_LOCAL_ACTION  Menu type -- An action specific to the parent, usually rendered as a link.
MENU_LOCAL_TASK  Menu type -- A task specific to the parent item, usually rendered as a tab.
MENU_NORMAL_ITEM  Menu type -- A "normal" menu item that's shown in menu and breadcrumbs.
MENU_SUGGESTED_ITEM  Menu type -- A normal menu item, hidden until enabled by an administrator.
 * @param string $submenu: (optional) a subsection of the menu structure to return RAW (unprocessed)
 */
function rweb_menu($submenu = '') {

  $items = array(
    'summary' => ['norm', t('Summary'), 'Summary', 'read'],

    'charge' => ['norm', t('Charge'), 'Tx 1', 'sell ok'],
    'charge/invoices' => ['sub', t('Upload Invoices'), 'InvoiceUpload', 'co sell ok'],
    'charge/nonmember' => ['call', t('Charge Nonmember'), 'TxNonmember', 'sell ok'],
    'pay' => ['norm', t('Pay'), 'Tx 1', 'buy ok'],
    'pay/payments' => ['sub', t('Upload Payments'), 'Payments', 'co buy ok'],
    'pay/payroll' => ['sub', t('Upload Payroll'), 'Payroll', 'co buy ok'],

    'get' => ['norm', t('Bank'), 'Get 1', 'manage ok'],
    
    'invest' => ['norm', t('Invest'), 'Invest', 'manage ok'],
    'invest/overview' => ['sub', t('Investment Club Overview'), 'Invest 1', 'manage ok', '', t(), 'eye-open'],
    'invest/list' => ['sub', t('List Investments'), 'InvestList 2', 'manage ok investor', '', t(), 'list'],
    'invest/cashout' => ['sub', t('Handle Cashout Requests'), 'InvestCashout 2', 'manage ok iclub', '', t(), 'new-window'],
    'invest/dividends' => ['sub', t('Issue Dividends'), 'InvestDividends 2', 'manage ok iclub', '', t(), 'cloud-download'],
    'invest/propose' => ['sub', t('Propose Investment'), 'InvestPropose 2', 'ok iclub', '', t(), 'fire'],
    'invest/buy-or-sell' => ['call', t('Buy or Sell Investment'), 'InvestBuySell 2', 'manage ok iclub', '', t(), 'refresh'],
    'invest/rate' => ['call', t('Rate Investment'), 'InvestRate 2', 'manage ok investor', '', t(), 'search'],

    'history' => ['norm', t('History'), 'History', 'read'],
    'history/transactions' => ['sub', t('Transactions'), 'Txs 2', 'read', '', t(), 'list'],
    'history/recurring' => ['sub', t('Recurring Payments'), 'Recurring', 'read', '', t(), 'list'],
    'history/invoices-to' => ['sub', t('Invoices TO You'), 'Invoices to', 'read', '', t(), 'log-in'],
    'history/invoices-from' => ['sub', t('Invoices FROM You'), 'Invoices from', 'read', '', t(), 'log-out'],
    'history/company-reports' => ['sub', t('Company Reports'), 'Data 2 co', 'read co', '', t(), 'signal'],
    'history/company-reports/demographics' => ['call', t('Customer Demographics'), 'Demographics', 'read co'],
    'history/statements' => ['sub', t('Statements'), 'Statements 2', 'read', '', t(), 'list-alt'],
    'history/notices' => ['sub', t('Notices'), 'Notices 2', 'read', '', t(), 'envelope'],
    'history/tax-info' => ['sub', t('Tax Info'), 'TaxInfo 2', 'read', '', t(), 'pawn'],
    'history/changes' => ['sub', t('See Changes'), 'SeeChanges', 'cadmin', '', t(), 'refresh'],
    'history/statement' => ['call', t('Statement'), '2', 'read', 'statement'],
    'history/customer-statement' => ['call', t('Customer Statement'), '2', 'read', 'custStatement'],

//    'history/notice' => ['call', t('Notice'), 'Notice 2', 'read'],
    
//    'community' => ['norm', t('Community'), 'FindCo', ANY],
    'community' => ['norm', t('Community'), 'Community', ANY],
    'community/invite' => ['sub', t('Invite / Endorse'), 'Invite 2', ANY, '', t(), 'share-alt'],
    'community/invite/all' => ['call', t('Shouters'), 'Shouters 3', ANY],
    'community/invite/example' => ['call', t('Invite Someone'), '', 'ok manage', 'inviteExample'],
    'community/invite/print' => ['call', t('Print Invite'), '', 'manage', 'printInvite'],
    'community/invite/invited-whom' => ['call', 'Invited Whom', 'InvitedWhom', 'manage'],
    'community/stepup' => ['sub', t('Step Up'), 'StepUp 2', 'manage', '', t(), 'export'],
    'community/crumbs' => ['sub', t('Share When You Receive'), 'Crumbs 2', 'manage', '', t(), 'import'],
    'community/buy-credit' => ['sub', t('Buy Credit for Later'), 'BuyCredit 2', 'manage', '', t(), 'time'],
    'community/donate' => ['sub', t('Donate to %PROJECT'), 'Donate', 'manage', '', t(), 'thumbs-up'],
    'community/coupons' => ['sub', t('Discount / Gift Certificates'), 'Coupons 2', 'manage', '', t(), 'usd'],
    'community/coupons/print' => ['call', t('Print Coupons'), '3', 'ok manage', 'couponsPrint'],
    'community/coupons/list' => ['call', t('List Discounts and Gift Cards'), 'CouponsList 3', 'manage'],
    'community/discount' => ['call', t('Simplified Discounts'), 'Discount', 'manage', '', t(), 'usd'],
    'community/posts' => ['sub', t('Offers, Needs, & Tips'), 'Posts 2', ANY, '', t(), 'heart'],
    'community/data' => ['sub', t('Community & Money Data'), 'Data 2', 'read', '', t(), 'list-alt'],
    'community/events' => ['sub', t('Democracy Events'), 'Events 2', 'ok manage', '', t(), 'bell'],
    
    'community/events/event' => ['call', t('Add/Edit Event'), 'Event 3 4', 'ok'],
    'community/events/question' => ['call', t('Add/Edit Question'), 'Question 3', 'cadmin'],
    'community/events/option' => ['call', t('Add/Edit Option'), 'Option 3', 'cadmin'],
    'community/events/proposal' => ['call', t('Funding Proposal'), 'Proposal 3', ANY],
    'community/events/proposal-report' => ['call', t('Proposal Report'), 'ProposalReport 3', 'manage'],
    'community/events/proposal-notes' => ['call', t('Proposal Notes'), 'ProposalNotes 3', 'manage'],
    
    'community/agreement' => ['sub', t('The Agreement'), 'Agreement', ANY, '', t(), 'globe'],
    'community/backing' => ['call', t('Backing Promise'), 'Backing', ANY, '', t(), 'knight'],
    'community/honors' => ['sub', t('Honored & Remembered'), 'Honors', ANY, '', t(), 'grain'],
    'community/message' => ['sub', t('Message a Member'), 'Message', 'ok refund', '', t(), 'envelope'],
    'community/find-company' => ['sub', t('Find a Company'), 'FindCo 2', ANY, '', t(), 'search'],
// temporarily disabled    'community/grant' => ['sub', t('Get Paid to Organize'), 'Grant', 'prose', '', t(), 'apple'],
//    'community/funds' => ['sub', t('Funds in Each Community'), 'CttyFunds', ANY, '', t(), 'usd'],
    'community/graphs' => ['sub', t('%PROJECT Graphs'), 'Graphs 2', 'cadmin', '', t(), 'stats'],
    'community/balance-sheet' => ['sub', t('Balance Sheet'), 'BalanceSheet 2', ANY, '', t(), 'pause'],
    'community/flags' => ['sub', t('Risk Flags'), 'Flags 2', ANY, '', t(), 'flag'],
    'community/chart-data' => ['call', t('Chart Data'), '2', ANY, 'chartData'],
    'community/list' => ['call', t('Community List'), '', ANY, 'cttyList'], // for charts/graphs
    
    'co' => ['norm', t('Company'), 'Co', 'manage co'],
    'co/cgbutton' => ['sub', t('Create CGPay Button'), 'CGButton 1', 'manage', '', t(), 'unchecked'],
    'co/coupons' => ['sub', t('Discount / Gift Certificates'), 'Coupons 2', 'manage', '', t(), 'usd'],
    'co/relations' => ['sub', t('Authorized Users'), 'Relations 2', 'manage -depends', '', t(), 'magnet'],
    'co/reports' => ['sub', t('Company Reports'), 'Data 2 co', 'read co', '', t(), 'signal'],
    'co/settings' => ['sub', t('Company Settings'), 'Company 2', 'manage co -depends', '', t(), 'calendar'],
    
    'settings' => ['norm', t('Settings'), 'Settings', 'manage -closed -depends'],
//    'settings/settings' => ['dft', t('Settings'), 'Settings', 'manage'],
    'settings/contact' => ['sub', t('Contact Info'), 'Contact', 'manage -depends', '', t(), 'user'],
    'settings/preferences' => ['sub', t('Preferences'), 'Prefs', 'manage -depends', '', t(), 'cog'],
    'settings/security' => ['sub', t('Security'), 'Security 2', 'manage -co -depends', '', t(), 'link'],
    'settings/fund' => ['sub', t('Banking'), 'Connect 2', 'manage -depends', '', t(), 'piggy-bank'],
    'settings/company' => ['sub', t('Company Info'), 'Company 2', 'manage co -depends', '', t(), 'calendar'],
    'settings/relations' => ['sub', t('Relations'), 'Relations 2', 'manage -depends', '', t(), 'magnet'],
// DISABLE FOR now()    'settings/boxes' => ['sub', t('Devices'), 'Boxes', 'manage -depends', '', t(), 'phone'],
    'settings/proxies' => ['sub', t('Proxies'), 'Proxies', 'manage -co -depends', '', t(), 'thumbs-up'],

    'reset' => ['call', t('Choose New Password'), 'ResetPassword 1', ANY],
    'settings/skip' => ['call', t('Skip Step'), '', 'manage', 'skipStep'],
    'settings/notifications' => ['call', t('Notifications'), 'Notifications', 'manage'],
    'settings/ssn' => ['call', t('Correct SSN'), 'Ssn 2', 'manage'],
    'settings/password' => ['call', t('Request New Password'), 'Pass 2', ANY],
    'settings/security/change-password' => ['call', 'Change Password', 'ChangePassword', 'manage'],
//    'settings/security/change-pin' => ['call', 'Change PIN', 'ChangePin', 'manage'],
    'settings/photo' => ['call', 'Photo', 'Photo 2', 'manage'],
    'settings/photo/upload' => ['call', 'Photo Upload', '3 4', ANY, 'photoUpload'],
//    'settings/verify-phone' => ['call', 'Verify Phone', 'VerifyPhone', 'manage dw'],
//    'settings/readd-phone' => ['call', 'reAdd Phone', '', 'manage dw', 'addPhone'],
    'settings/basic' => ['call', 'Basic', 'Basic', 'manage'],
//    'settings/kba' => ['call', 'Kba', 'Kba', 'manage dw'],
//    'settings/photo-id' => ['call', 'Kba', 'PhotoId', 'manage'],
    'settings/proxy' => ['call', 'Proxy', 'Proxy 2', 'manage -co'],
    'settings/verifyid' => ['call', 'Correct SSN', 'VerifyId 2', 'manage'],
    'settings/verifyemail' => ['call', 'Verify Email', 'VerifyEmail 2', ANY],
    'settings/work' => ['call', 'Work Life', 'Work 2', 'manage'],
    'settings/agent' => ['call', 'Choose an Agent', 'Agent 2', 'manage'],
    'settings/resend' => ['call', 'Resend Email', 'Resend', 'manage'],
    'settings/food' => ['call', 'Food Fund', 'Food 2', ANY],
    'settings/partnersteptwo' => ['call', 'Partner Signup Agreement Etc.', 'PartnerStepTwo', 'manage'],
    'settings/partnerend' => ['call', 'Finish Partner Signup', 'PartnerSignup end=1', ANY],

//    'handy' => isDEV ? ['norm', t('Handy'), '', 'dev', 'handyLinks'] : NULL,
    'tests' => isDEV ? ['norm', t('Test'), '1', 'dev', 'tests'] : NULL,
//    'php' => isDEV ? ['norm', t('PHP'), 'Php', 'dev'] : NULL,
    
    'menu' => ['call', t('Menu'), 'Menu', ANY],
    'empty' => ['call', t('Empty'), 'Empty 1', ANY],
    'prox' => ['call', t('Prox'), 'Prox 1 2', ANY], // proxy form called from rdo()

    'request-employee-rcard' => ['call', t('Request Employee %PROJECT Card'), 'RequestRCard 1', 'manage'],
    
    'I' => ['call', 'Scanned QR', 'I', ANY],
    
    'prejoin' => ['call', 'Open a Joint Account', 'Prejoin', 'manage'],
    'handle-invoice' => ['call', 'Handle Invoice', 'HandleInvoice 1', ANY],
    'rerisk' => ['call', 'Recalculate Risk', 'Rerisk 1 2 3', 'cadmin2'],
    
    'sadmin' => ['norm', t('Admin'), 'Admin', isDEV ? ANY : 'admin2'],
    'sadmin/panel' => ['sub', t('Panel'), 'AdminPanel 2', 'cadmin'],
    'sadmin/followup' => ['sub', t('Admin Action Page'), 'Followup', 'admin2'],
    'sadmin/member-list' => ['sub', t('Member List'), 'MemberList', 'cadmin2'],
    'sadmin/export-list' => ['sub', t('Export'), 'DownloadMemberList 2', 'cadmin2'],
    'sadmin/deposits' => ['sub', t('Deposits'), 'Deposits', 'superadmin'],
    'sadmin/new-member' => ['sub', t('New Member'), 'Signup code=.(admin)', 'cadmin'],
    'sadmin/make-community' => ['sub', t('Make Ctty'), 'MakeCtty', 'superadmin'],
    'sadmin/groups' => [isDEV ? 'sub' : 'call', t('Groups'), 'Groups 2', 'admin'],
    'sadmin/rules' => [isDEV ? 'sub' : 'call', t('Rules'), 'Rules 2', 'admin'],
    'sadmin/check-sanity' => [isDEV ? 'sub' : 'call', 'Check database consistency', '0', 'admin', 'checkSanity'],
//    'sadmin/sms' => ['sub', t('Test SMS'), 'SMS', 'superadmin'],
    'sadmin/handy' => ['sub', t('Handy'), '', 'superadminORdev', 'handyLinks'],
    'sadmin/php' => ['sub', t('PHP'), 'Php 2', 'superadminORdev'],

    'sadmin/tx-info' => ['call', 'Transaction Info', 'TxInfo 2', 'admin2'],
    'sadmin/deposit-details' => ['call', t('Deposit Details'), '2', 'superadmin', 'depositDetails'],
    'sadmin/checks' => ['call', t('Checks'), '2', 'superadmin', 'printChecks'],
    'sadmin/achs' => ['call', t('ACHs'), '2', 'superadmin', 'achBatch'],
    'sadmin/changes' => ['call', t('See Changes'), 'SeeChanges 2', 'cadmin'],
		'sadmin/reconcile-ctty-fund' => ['call', t('Reconcile Community Fund'), 'ReconcileCttyFund', 'superadmin'],
    'sadmin/reconcile-ctty-fund/manually' => ['call', t('Reconcile Manually'), 'ReconcileManually 3', 'superadmin'],
    'rcredits/util' => ['call', 'Util', '2', 'superadminORdev', 'util'],
    'sadmin/delete-account' => ['call', t('Delete Account'), '2', 'superadmin', 'deleteAccount'],
    'sadmin/variables' => ['call', t('List/Edit Variables'), 'Variables', 'superadmin'],
    'sadmin/variables/edit' => ['call', t('Edit Variable'), 'VariableEdit', 'superadmin'],
    'print-rcard' => ['call', t('Print ID Card'), '1 2', 'cadmin', 'memberID'],
    'sadmin/show-deposits' => ['call', t('Show Deposits'), 'ShowDeposits', 'read'],
    'sadmin/show-reconciled' => ['call', t('Show Reconciled'), 'ShowReconciled', 'read'],
    'sadmin/test-results' => ['call', t('Test Results'), 'TestResults', 'dev'], // also go here manually, if needed

    'signout' => ['norm', t('Sign out'), '', 'signedIn', 'signout'],
    'signin' => ['norm', t('Sign in'), 'Signin', '-signedIn'],
//    'signin' => ['call', 'Sign in', 'Signin', ANY],
//    'sinx' => ['call', 'Sign in from elsewhere', 'Sinx', ANY],
    
    'account-photo' => ['call', 'Account Photo', 'AccountPhoto 0 1', ANY],
    'account-thumb' => ['call', 'Account Photo Thumbnail', 'AccountPhoto 0 1', ANY],
    'help' => ['call', t('Help'), 'Help 1 2', ANY],
    'cgbiz' => ['call', t('Common Good Business'), 'CgBiz 1', ANY],
    'change-account' => ['call', t('Change Who'), '1', ANY, 'changeWho'],
    'status' => ['call', 'Status', 'Membership 1', 'manage'],
    'signup' => ['call', t('Sign Up For %PROJECT'), 'Signup', ANY],
    'signup-co' => ['call', t('Open a Company Account'), 'SignupCo', ANY],
    'menu' => ['call', 'Main Menu', 'Menu', ANY],
    'member' => ['call', 'Company Profile', 'Profile', ANY],
    'do' => ['call', 'Do', '1 2', ANY, 'rdo'],
    'coup' => ['call', t('Disable account'), '1', ANY, 'coup'],

    'pos' => ['call', 'POS', '1', ANY, 'pos'], // called from the CGPay app
    'ajax' => ['call', 'AJAX', '1', ANY, 'ajax'], // called from the CGPay app
    'whosin' => ['call', t('Who\'s in?'), '1', ANY, 'whosin'], // called from promo site
    'secret' => ['call', 'Secret', '', ANY, 'secrets'],
    'error' => ['call', 'System Error', '1', ANY, 'error'],
    'page-not-found' => ['call', t('Page Not Found'), 'PageNotFound', ANY],
    'go2' => ['call', t('Go to 2 pages'), '1', ANY, 'go2'],
    'pay-with-cg' => ['call', t('Pay With %RCREDITS'), 'Buy 1', ANY],
    'authcode' => ['call', t('Supply a one-use auth code'), '', ANY, 'authcode'],
    'scraps' => ['call', 'Scraps', 'Scraps 1', ANY],   
    'partner' => ['call', 'Signup Through Partner', 'PartnerSignup 1', ANY],
    'accounts' => isDEV ? ['call', 'Account Choices', 'Accounts', 'manage'] : NULL,
    'redirect' => ['call', 'Redirect', '', ANY, 'redirect'],
    'mailus' => ['call', t('Mail %PROJECT'), 'MailUs 1', ANY],
    'unsubscribe' => ['call', t('Unsubscribe'), 'Unsubscribe 1', ANY],
  );

  foreach ($items as $k => $v) {
    if ($submenu) {
      if (u\starts($k, "$submenu/")) $menu[$k] = $v;
    } elseif ($v) $menu[$k] = makeMenuItem($k, $v);
  }
  
  return $menu;
}

function rweb_menu_alter(&$items) {
  foreach (ray('node user/password user/register') as $one) unset($items[$one]);
}
