INSERT INTO `r_industries` (`iid`, `industry`, `parent`) VALUES
(1, 'Art / Culture / Science', NULL),
(2, 'Food', NULL),
(3, 'Business and Industry', NULL),
(4, 'Building / Construction / Hardware', NULL),
(5, 'Family, Community, and Society', NULL),
(6, 'Education', NULL),
(7, 'Money', NULL),
(8, 'Information and Communications', NULL),
(9, 'Sports and Recreation', NULL),
(10, 'Energy and Fuel', NULL),
(11, 'Health', NULL),
(12, 'Transportation', NULL),
(13, 'Place', NULL),
(14, 'Retail', NULL),
(15, 'Other Services', NULL),

(16, 'Visual Artists', 1),
(17, 'Performance Artists', 1),
(18, 'Museums and Galleries', 1),
(19, 'Visual Art', 1),
(20, 'Theaters and Performing Arts', 1),
(21, 'Arts and Crafts Supplies', 1),

(22, 'Farms', 2),
(23, 'Grocers', 2),
(24, 'Restaurants and Catering', 2),
(25, 'Food Processing and Distribution', 2),

(26. 'Engineering', 3),
(27, 'Office Supplies', 3),
(28, 'Computer Services', 3),
(29, 'Manufacturing and Mining', 3),
(30, 'Industrial Supplies and Materials', 3),
(31, 'Business Services and Associations', 3),
(32, 'Wholesale', 3),

(33, 'Hardware and Building Supplies', 4),
(34, 'Plumbing / Heating / Cooling', 4),
(35, 'Electrical and Lighting', 4),
(36, 'Contractors', 4),
(37, 'Construction Equipment', 4),

(38, 'Family and Human Services', 5),
(39, 'Community Organizations', 5),
(40, 'Government', 5),
(41, 'Law', 5),

(42,'Educational Adventures', 6),
(43, 'Schools and Colleges', 6),

(44, 'Credit Unions and Banks', 7),
(45, 'Insurance', 7),
(46, 'Financial Services', 7),

(47, 'Media', 8),
(48, 'Internet', 8),
(49, 'Libraries', 8),
(50, 'Computer and Electronics', 8),

(51, 'Hobbies', 9),
(52, 'Sports Equipment', 9),
(53, 'Liquor, Tobacco, and Other Recreational Drugs', 9),

(54, 'Solar, Wind, and Alternative Energy', 10),
(55, 'Propane and Oil', 10),
(56, 'Gasoline', 10),

(57, 'Gyms', 11),
(58, 'Therapists', 11),
(59, 'Hospitals / Clinics / Doctors / Midwives', 11),
(60, 'Medical Supplies and Drugstores', 11),

(61, 'Public Transit, Carpooling, and Buses', 12),
(62, 'Bicycles', 12),
(63, 'Cars / Automobiles', 12),
(64, 'Automotive Services', 12),

(65, 'Housing', 13),
(66, 'Accommodations', 13),
(67, 'Facilities', 13),
(68, 'Real Estate', 13),
(69, 'Architects', 13),

(70, 'Department Stores', 14),
(71, 'Bookstores', 14),
(72, 'Furniture', 14),
(73, 'Appliances', 14),
(74, 'Clothing', 14),
(75, 'Consumer Electronics', 14),
(76, 'Toys and Games', 14),
(77, 'Other Retail', 14),

(78, 'Farm Equipment and Supplies', 22);
